list(APPEND SRCS qtusercore/module/commandcenter.cpp
				 qtusercore/module/commandcenter.h
				 qtusercore/module/csvwriter.cpp
				 qtusercore/module/job.cpp
				 qtusercore/module/jobexecutor.cpp
				 qtusercore/module/jobthread.cpp
				 qtusercore/module/metacreator.cpp
				 qtusercore/module/profiler.cpp
				 qtusercore/module/progressor.cpp
				 qtusercore/module/progressortracer.cpp
				 qtusercore/module/settingcache.cpp
				 qtusercore/module/singleton.cpp
				 qtusercore/module/statenotifier.cpp
				 qtusercore/module/systemutil.cpp
				 qtusercore/module/timestamp.cpp
				 qtusercore/module/translatenotifier.cpp
				 qtusercore/module/csvwriter.h
				 qtusercore/module/job.h
				 qtusercore/module/jobexecutor.h
				 qtusercore/module/jobthread.h
				 qtusercore/module/metacreator.h
				 qtusercore/module/profiler.h
				 qtusercore/module/progressor.h
				 qtusercore/module/progressortracer.h
				 qtusercore/module/settingcache.h
				 qtusercore/module/singleton.h
				 qtusercore/module/statenotifier.h
				 qtusercore/module/systemutil.h
				 qtusercore/module/timestamp.h
				 qtusercore/module/translatenotifier.h
				 qtusercore/module/cxhandlerbase.h
				 qtusercore/module/cxhandlerbase.cpp
				 qtusercore/module/cxopenandsavefilemanager.h
				 qtusercore/module/cxopenandsavefilemanager.cpp
				 qtusercore/module/creativeinterface.h
				 qtusercore/module/creativeplugincenter.h
				 qtusercore/module/creativeplugincenter.cpp
				 qtusercore/module/openglcontextsaver.h
				 qtusercore/module/openglcontextsaver.cpp
				 )